owner: OpenCourseAPI
repo: status

sites:
  - name: API
    url: https://opencourse.dev/fh # TODO: add actual health check endpoint
  - name: Website
    url: https://opencourse.dev

status-website:
  # cname: status.opencourse.dev
  baseUrl: /status
  logoUrl: https://avatars.githubusercontent.com/u/40309595?s=200&v=4
  name: OpenCourseAPI
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
